# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pl'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: pl
    app.notifications.email_sender: anonymous@example.com

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    YourFrog\App\:
        resource: '../src/App'
        exclude: '../src/{DependencyInjection,Entity,Tests}'

    YourFrog\Panel\:
        resource: '../src/Panel'
        exclude: '../src/{DependencyInjection,Entity,Tests}'

    YourFrog\Website\:
        resource: '../src/Website'
        exclude: '../src/{DependencyInjection,Entity,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    YourFrog\Website\Controller\:
        resource: '../src/Website/Controller'
        tags: ['controller.service_arguments']

    YourFrog\Panel\Repository\Contest\SettingsRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - YourFrog\Panel\Entity\Contest\Settings

    YourFrog\App\Repository\Security\AccountAuthenticationHistoryRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - YourFrog\App\Entity\Security\AccountAuthenticationHistory

    YourFrog\App\Security\CounterOfLoginFailsChecker:
        arguments:
            - "%app.security.maximum_login_fails%"

    YourFrog\App\Service\Authentication\StoreIP:
        class: YourFrog\App\Service\Authentication\KeepAuthentication
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            - { name: kernel.event_listener, event: security.authentication.failure, method: onSecurityFailure }